language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '7.5'
before_script:
  - npm prune && npm cache clean
script:
  - yarn run test
